### ISSUE TITLE
playback error

### ISSUE THREAD

**Issue by rsignell-usgs** [friedrichknuth/ooi_local_processing#3]
Subprocess was giving 127, but eventually I figured out that I need to specify the full path name to `analyze` and `playback`  because those are not in the default python environment, since I'm on JupyterHub. 

So the `analyze` part worked, but when I tried `playback` from the command prompt, and got this error:
```
(mi) rsignell@0e6be50c3dc2:/notebooks/rsignell/ooi_local_processing$ playback datalog mi.instrument.seabird.sbe16plus_v2.ctdpf_sbe43.driver \
 RS01SBPS-SF01A-2A-CTDPFA102 log:// csv:// ./raw_data/CTDPFA102_10.33.3.195_2101_20171005T0000_UTC.dat
2017-10-16 21:05:00,063 INFO     mi.core.instrument.publisher Publisher: max_events: 500 publish_interval: 5
2017-10-16 21:05:00,349 INFO     mi.core.instrument.publisher Publisher: max_events: 500 publish_interval: 5
Traceback (most recent call last):
  File "/notebooks/rsignell/envs/mi/bin/playback", line 11, in <module>
    load_entry_point('mi-instrument==0.5.4', 'console_scripts', 'playback')()
  File "/notebooks/rsignell/envs/mi/lib/python2.7/site-packages/mi/core/instrument/playback.py", line 381, in main
    if zplsc_reader:
UnboundLocalError: local variable 'zplsc_reader' referenced before assignment
(mi) rsignell@0e6be50c3dc2:/notebooks/rsignell/ooi_local_processing
```

**Comment by rsignell-usgs** [comment]
@friedrichknuth could you try creating the environment using the simple approach in https://github.com/friedrichknuth/ooi_local_processing/issues/2#issuecomment-337040702 and see if you get the same error?    

I'm thinking that if that works for you, there might be some system packages sneaking in on your Mac.   

If it fails, then I guess that simpler approach to creating the environment is not sufficient.

**Comment by friedrichknuth** [comment]
This is due to a variable being reference before it is assigned. I submitted a fix to mi-instrument, but it has not yet been merged yet by the system administration team.

https://github.com/oceanobservatories/mi-instrument/pull/31

You can add lines 367 through 369 to mi/core/instrument/playback.py, as specified in the change log

https://github.com/oceanobservatories/mi-instrument/pull/31/files

Then cd to mi-instrument and `pip install --no-deps -U .` to update the environment installation. Make sure you have your environment activated when doing so.

I think that should do it, if not just recreate the environment after modifying mi/core/instrument/playback.py

**Comment by rsignell-usgs** [comment]
Fixed in https://github.com/oceanobservatories/mi-instrument/pull/31
